"""Project template generation."""

from __future__ import annotations

from pathlib import Path

from robot_studio.domain.models import ProjectType
from robot_studio.infrastructure.project.filesystem import (
    FilesystemProjectProvider,
    ProjectValidationError,
)


class TemplateService:
    def __init__(self, filesystem: FilesystemProjectProvider | None = None) -> None:
        self._fs = filesystem or FilesystemProjectProvider()

    def apply(self, project_root: Path, name: str, project_type: ProjectType) -> None:
        if project_root.exists() and any(project_root.iterdir()):
            raise ProjectValidationError(
                f"A project named '{name}' already exists",
            )

        project_root.mkdir(parents=True, exist_ok=True)
        self._fs.ensure_project_dirs(project_root)

        if project_type == ProjectType.EMPTY:
            return

        if project_type == ProjectType.BROWSER:
            self._write_common(project_root, name, "Browser Automation")
            self._write_requirements(
                project_root,
                ["robotframework", "robotframework-browser"],
            )
            self._write_file(
                project_root / "tests" / "sample.robot",
                _BROWSER_SAMPLE,
            )
            return

        if project_type == ProjectType.API:
            self._write_common(project_root, name, "API Testing")
            self._write_requirements(
                project_root,
                ["robotframework", "robotframework-requests"],
            )
            self._write_file(
                project_root / "tests" / "sample.robot",
                _API_SAMPLE,
            )
            return

        if project_type == ProjectType.SELENIUM:
            self._write_common(project_root, name, "Selenium")
            self._write_requirements(
                project_root,
                ["robotframework", "robotframework-seleniumlibrary"],
            )
            self._write_file(
                project_root / "tests" / "sample.robot",
                _SELENIUM_SAMPLE,
            )
            return

        raise ProjectValidationError(f"Unknown project type: {project_type}")

    def _write_common(self, project_root: Path, name: str, label: str) -> None:
        self._write_file(
            project_root / "README.md",
            (
                f"# {name}\n\n"
                f"Robot Framework {label} project generated by Robot Studio.\n\n"
                "Starter folders:\n"
                "- `tests/` — test suites\n"
                "- `resources/` — shared keywords and resources\n"
                "- `variables/` — shared variables\n"
            ),
        )

    def _write_requirements(self, project_root: Path, packages: list[str]) -> None:
        content = "\n".join(packages) + "\n"
        self._write_file(project_root / "requirements.txt", content)

    @staticmethod
    def _write_file(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


_BROWSER_SAMPLE = """*** Settings ***
Documentation    Sample Browser Library suite
Library          Browser

*** Test Cases ***
Open Example Page
    New Browser    chromium    headless=True
    New Page    https://example.com
    Get Title    ==    Example Domain
    Close Browser
"""

_API_SAMPLE = """*** Settings ***
Documentation    Sample API suite
Library          RequestsLibrary

*** Test Cases ***
Get Example Endpoint
    Create Session    example    https://jsonplaceholder.typicode.com
    ${response}=    GET On Session    example    /todos/1
    Status Should Be    200    ${response}
"""

_SELENIUM_SAMPLE = """*** Settings ***
Documentation    Sample SeleniumLibrary suite
Library          SeleniumLibrary

*** Test Cases ***
Open Example Page
    Open Browser    https://example.com    headlesschrome
    Title Should Be    Example Domain
    Close Browser
"""
